FROM php:7.4-fpm

RUN apt update
RUN apt install -y curl
RUN apt update
RUN apt install -y zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN docker-php-ext-install opcache
RUN apt install -y libmagickwand-dev --no-install-recommends
RUN pecl install -o -f imagick
RUN docker-php-ext-enable imagick

WORKDIR /usr/share/nginx/html