version: '3'

services:
  nginx:
    image: nginx:latest
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    container_name: pagespeed-nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/prod.conf:/etc/nginx/conf.d/prod.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./code:/usr/share/nginx/html

  php:
    build:
      context: ./
      dockerfile: Dockerfile-php
    ports:
      - "9000:9000"
    container_name: pagespeed-php
    volumes:
      - ./config/php/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./code:/usr/share/nginx/html
